databases:
  - name: blog_app_db
    databaseName: blog_app
    user: blog_app_user
    plan: free

services:
  - type: web
    name: blog_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_app_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
